services:
  precalc:
    build: precalculus
    volumes:
      - ./out:/out
  site:
    build: site
    volumes:
      - ./out:/out
    depends_on:
      precalc:
        condition: service_completed_successfully
