name: Publish Pdfs

on:
  push:
    branches:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build Images
        run: docker compose build --no-cache
        
      - name: Build PDFs
        run: docker compose up

      - name: Publish
        uses: dmnemec/copy_file_to_another_repo_action@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source_file: 'output'
          destination_repo: 'gucciwang123/gucciwang123.github.io'
          user_email: 'wangtyler123@gmail.com'
          user_name: 'gucciwang123'
          commit_message: 'Updated notes'
        

